export const APP_TYPES = {
  UPDATE_USER: 'ORDERING/UPDATE_USER',

  // get OTP
  RESET_GET_OTP_REQUEST: 'ORDERING/APP/RESET_GET_OTP_REQUEST',
  GET_OTP_REQUEST: 'ORDERING/APP/GET_OTP_REQUEST',
  GET_OTP_SUCCESS: 'ORDERING/APP/GET_OTP_SUCCESS',
  GET_OTP_FAILURE: 'ORDERING/APP/GET_OTP_FAILURE',

  // get phone WhatsApp support
  GET_WHATSAPPSUPPORT_REQUEST: 'ORDERING/APP/GET_WHATSAPPSUPPORT_REQUEST',
  GET_WHATSAPPSUPPORT_SUCCESS: 'ORDERING/APP/GET_WHATSAPPSUPPORT_SUCCESS',
  GET_WHATSAPPSUPPORT_FAILURE: 'ORDERING/APP/GET_WHATSAPPSUPPORT_FAILURE',

  // OTP
  RESET_SEND_OTP_REQUEST: 'ORDERING/APP/RESET_SEND_OTP_REQUEST',
  SEND_OTP_REQUEST: 'ORDERING/APP/SEND_OTP_REQUEST',
  SEND_OTP_SUCCESS: 'ORDERING/APP/SEND_OTP_SUCCESS',
  SEND_OTP_FAILURE: 'ORDERING/APP/SEND_OTP_FAILURE',
};
