export const APP_TYPES = {
  CLEAR_ERROR: "LOYALTY/APP/CLEAR_ERROR",

  // fetch onlineStoreInfo
  FETCH_ONLINESTOREINFO_REQUEST: "LOYALTY/APP/FETCH_ONLINESTOREINFO_REQUEST",
  FETCH_ONLINESTOREINFO_SUCCESS: "LOYALTY/APP/FETCH_ONLINESTOREINFO_SUCCESS",
  FETCH_ONLINESTOREINFO_FAILURE: "LOYALTY/APP/FETCH_ONLINESTOREINFO_FAILURE",

  // fetch business
  FETCH_BUSINESS_REQUEST: "LOYALTY/APP/FETCH_BUSINESS_REQUEST",
  FETCH_BUSINESS_SUCCESS: "LOYALTY/APP/FETCH_BUSINESS_SUCCESS",
  FETCH_BUSINESS_FAILURE: "LOYALTY/APP/FETCH_BUSINESS_FAILURE",

  // message modal
  SET_MESSAGE_INFO: "LOYALTY/APP/SET_MESSAGE_INFO",
  SHOW_MESSAGE_MODAL: "LOYALTY/APP/SHOW_MESSAGE_MODAL",
  HIDE_MESSAGE_MODAL: "LOYALTY/APP/HIDE_MESSAGE_MODAL",
  // set cashback message
  SET_CASHBACK_MESSAGE_SUCCESS: 'LOYALTY/HOME/SET_CASHBACK_MESSAGE_SUCCESS',

  // clear cashback message
  CLEAR_CASHBACK_MESSAGE_SUCCESS: 'LOYALTY/HOME/CLEAR_CASHBACK_MESSAGE_SUCCESS',

  // fetch login status
  FETCH_LOGIN_STATUS_REQUEST: 'LOYALTY/APP/FETCH_LOGIN_STATUS_REQUEST',
  FETCH_LOGIN_STATUS_SUCCESS: 'LOYALTY/APP/FETCH_LOGIN_STATUS_SUCCESS',
  FETCH_LOGIN_STATUS_FAILURE: 'LOYALTY/APP/FETCH_LOGIN_STATUS_FAILURE',

  // login
  CREATE_LOGIN_REQUEST: 'LOYALTY/APP/CREATE_LOGIN_REQUEST',
  CREATE_LOGIN_SUCCESS: 'LOYALTY/APP/CREATE_LOGIN_SUCCESS',
  CREATE_LOGIN_FAILURE: 'LOYALTY/APP/CREATE_LOGIN_FAILURE',
  CLEAR_TOKENS: 'LOYALTY/APP/CLEAR_TOKENS',

  // get OTP
  GET_OTP_REQUEST: 'LOYALTY/APP/GET_OTP_REQUEST',
  GET_OTP_SUCCESS: 'LOYALTY/APP/GET_OTP_SUCCESS',
  GET_OTP_FAILURE: 'LOYALTY/APP/GET_OTP_FAILURE',

  // OTP
  RESET_OTP_STATUS: 'LOYALTY/APP/RESET_OTP_STATUS',
  CREATE_OTP_REQUEST: 'LOYALTY/APP/CREATE_OTP_REQUEST',
  CREATE_OTP_SUCCESS: 'LOYALTY/APP/CREATE_OTP_SUCCESS',
  CREATE_OTP_FAILURE: 'LOYALTY/APP/CREATE_OTP_FAILURE',

  // Set login prompt
  SET_LOGIN_PROMPT: 'LOYALTY/APP/SET_LOGIN_PROMPT',


  // Fetch customer profile
  FETCH_CUSTOMER_PROFILE_REQUEST: 'LOYALTY/APP/FETCH_CUSTOMER_PROFILE_REQUEST',
  FETCH_CUSTOMER_PROFILE_SUCCESS: 'LOYALTY/APP/FETCH_CUSTOMER_PROFILE_SUCCESS',
  FETCH_CUSTOMER_PROFILE_FAILURE: 'LOYALTY/APP/FETCH_CUSTOMER_PROFILE_FAILURE',
};

export const HOME_TYPES = {
  // set customerId
  SET_CUSTOMER_ID_SUCCESS: 'LOYALTY/HOME/SET_CUSTOMER_ID_SUCCESS',

  // get cashback histories
  GET_CASHBACK_HISTORIES_REQUEST: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_REQUEST',
  GET_CASHBACK_HISTORIES_SUCCESS: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_SUCCESS',
  GET_CASHBACK_HISTORIES_FAILURE: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_FAILURE',

  // receipt list
  FETCH_RECEIPT_LIST_REQUEST: "LOYALTY/HOME/FETCH_RECEIPT_LIST_REQUEST",
  FETCH_RECEIPT_LIST_SUCCESS: "LOYALTY/HOME/FETCH_RECEIPT_LIST_SUCCESS",
  FETCH_RECEIPT_LIST_FAILURE: "LOYALTY/HOME/FETCH_RECEIPT_LIST_FAILURE",
};

export const CLAIM_TYPES = {
  // fetch receiptNumber
  FETCH_RECEIPTNUMBER_REQUEST: 'LOYALTY/CLAIM/FETCH_RECEIPTNUMBER_REQUEST',
  FETCH_RECEIPTNUMBER_SUCCESS: 'LOYALTY/CLAIM/FETCH_RECEIPTNUMBER_SUCCESS',
  FETCH_RECEIPTNUMBER_FAILURE: 'LOYALTY/CLAIM/FETCH_RECEIPTNUMBER_FAILURE',

  // fetch CashbackInfo
  FETCH_CASHBACKINFO_REQUEST: 'LOYALTY/CLAIM/FETCH_CASHBACKINFO_REQUEST',
  FETCH_CASHBACKINFO_SUCCESS: 'LOYALTY/CLAIM/FETCH_CASHBACKINFO_SUCCESS',
  FETCH_CASHBACKINFO_FAILURE: 'LOYALTY/CLAIM/FETCH_CASHBACKINFO_FAILURE',

  // create CashbackInfo
  CREATE_CASHBACKINFO_REQUEST: 'LOYALTY/CLAIM/CREATE_CASHBACKINFO_REQUEST',
  CREATE_CASHBACKINFO_SUCCESS: 'LOYALTY/CLAIM/CREATE_CASHBACKINFO_SUCCESS',
  CREATE_CASHBACKINFO_FAILURE: 'LOYALTY/CLAIM/CREATE_CASHBACKINFO_FAILURE',
};