export const HOME_TYPES = {
	// set customerId
	SET_CUSTOMER_ID_SUCCESS: 'LOYALTY/HOME/SET_CUSTOMER_ID_SUCCESS',

	// get cashback histories
	GET_CASHBACK_HISTORIES_REQUEST: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_REQUEST',
	GET_CASHBACK_HISTORIES_SUCCESS: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_SUCCESS',
	GET_CASHBACK_HISTORIES_FAILURE: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_FAILURE',

	// set cashback message
	SET_CASHBACK_MESSAGE_SUCCESS: 'LOYALTY/HOME/SET_CASHBACK_MESSAGE_SUCCESS',

	// clear cashback message
	CLEAR_CASHBACK_MESSAGE_SUCCESS: 'LOYALTY/HOME/CLEAR_CASHBACK_MESSAGE_SUCCESS',
}