export const APP_TYPES = {
	CLEAR_ERROR: "LOYALTY/APP/CLEAR_ERROR",

	// fetch onlineStoreInfo
	FETCH_ONLINESTOREINFO_REQUEST: "LOYALTY/APP/FETCH_ONLINESTOREINFO_REQUEST",
	FETCH_ONLINESTOREINFO_SUCCESS: "LOYALTY/APP/FETCH_ONLINESTOREINFO_SUCCESS",
	FETCH_ONLINESTOREINFO_FAILURE: "LOYALTY/APP/FETCH_ONLINESTOREINFO_FAILURE",

	// fetch business
	FETCH_BUSINESS_REQUEST: "LOYALTY/APP/FETCH_BUSINESS_REQUEST",
	FETCH_BUSINESS_SUCCESS: "LOYALTY/APP/FETCH_BUSINESS_SUCCESS",
	FETCH_BUSINESS_FAILURE: "LOYALTY/APP/FETCH_BUSINESS_FAILURE",

	// message modal
	SHOW_MESSAGE_MODAL: "LOYALTY/APP/SHOW_MESSAGE_MODAL",
	HIDE_MESSAGE_MODAL: "LOYALTY/APP/HIDE_MESSAGE_MODAL",

	// fetch login status
	FETCH_LOGIN_STATUS_REQUEST: 'LOYALTY/APP/FETCH_LOGIN_STATUS_REQUEST',
	FETCH_LOGIN_STATUS_SUCCESS: 'LOYALTY/APP/FETCH_LOGIN_STATUS_SUCCESS',
	FETCH_LOGIN_STATUS_FAILURE: 'LOYALTY/APP/FETCH_LOGIN_STATUS_FAILURE',

	// login
	CREATE_LOGIN_REQUEST: 'LOYALTY/APP/CREATE_LOGIN_REQUEST',
	CREATE_LOGIN_SUCCESS: 'LOYALTY/APP/CREATE_LOGIN_SUCCESS',
	CREATE_LOGIN_FAILURE: 'LOYALTY/APP/CREATE_LOGIN_FAILURE',

	// get OTP
	GET_OTP_REQUEST: 'LOYALTY/APP/GET_OTP_REQUEST',
	GET_OTP_SUCCESS: 'LOYALTY/APP/GET_OTP_SUCCESS',
	GET_OTP_FAILURE: 'LOYALTY/APP/GET_OTP_FAILURE',

	// OTP
	CREATE_OTP_REQUEST: 'LOYALTY/APP/CREATE_OTP_REQUEST',
	CREATE_OTP_SUCCESS: 'LOYALTY/APP/CREATE_OTP_SUCCESS',
	CREATE_OTP_FAILURE: 'LOYALTY/APP/CREATE_OTP_FAILURE',

	// Set login prompt
	SET_LOGIN_PROMPT: 'LOYALTY/APP/SET_LOGIN_PROMPT',
};

export const HOME_TYPES = {
	// set customerId
	SET_CUSTOMER_ID_SUCCESS: 'LOYALTY/HOME/SET_CUSTOMER_ID_SUCCESS',

	// get cashback histories
	GET_CASHBACK_HISTORIES_REQUEST: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_REQUEST',
	GET_CASHBACK_HISTORIES_SUCCESS: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_SUCCESS',
	GET_CASHBACK_HISTORIES_FAILURE: 'LOYALTY/HOME/GET_CASHBACK_HISTORIES_FAILURE',

	// set cashback message
	SET_CASHBACK_MESSAGE_SUCCESS: 'LOYALTY/HOME/SET_CASHBACK_MESSAGE_SUCCESS',

	// clear cashback message
	CLEAR_CASHBACK_MESSAGE_SUCCESS: 'LOYALTY/HOME/CLEAR_CASHBACK_MESSAGE_SUCCESS',
};