export const EARNED_REWARDS_BASE_SPEND = 10;

export const CASHBACK_CREDITS_HISTORY_TYPES = {
  EARNED: 'earned',
  EXPENSE: 'expense',
  PENDING: 'pending',
  EXPIRED: 'expired',
  ADJUSTMENT: 'adjustment',
};

export const CASHBACK_CREDITS_HISTORY_REDUCE_TYPES = [
  CASHBACK_CREDITS_HISTORY_TYPES.EXPENSE,
  CASHBACK_CREDITS_HISTORY_TYPES.EXPIRED,
];

export const CASHBACK_CREDITS_HISTORY_LOG_I18N_KEYS = {
  [CASHBACK_CREDITS_HISTORY_TYPES.EARNED]: 'Earned',
  [CASHBACK_CREDITS_HISTORY_TYPES.EXPENSE]: 'Redeemed',
  [CASHBACK_CREDITS_HISTORY_TYPES.PENDING]: 'Pending',
  [CASHBACK_CREDITS_HISTORY_TYPES.EXPIRED]: 'Expired',
  [CASHBACK_CREDITS_HISTORY_TYPES.ADJUSTMENT]: 'Adjustment',
};

export const DATE_OPTIONS = {
  weekday: 'short',
  year: 'numeric',
  month: 'short',
  day: 'numeric',
};
