export const E_INVOICE_APP_CONTAINER_ID = 'e-invoice-app-container';

export const PATHS = {
  BASE: '/',
  E_INVOICE: '/e-invoice',
  CATEGORY: '/category',
  CONSUMER: '/consumer',
  BUSINESS: '/business',
  PROFILE: '/profile',
  FORM: '/edit',
  PREVIEW: '/preview',
  INVALID: '/invalid',
};

export const PAGE_ROUTES = {
  E_INVOICE: PATHS.BASE,
  CATEGORY: PATHS.CATEGORY,
  INVALID: PATHS.INVALID,
  CONSUMER_FORM: `${PATHS.CONSUMER}${PATHS.PROFILE}${PATHS.FORM}`,
  CONSUMER_PREVIEW: `${PATHS.CONSUMER}${PATHS.PROFILE}${PATHS.PREVIEW}`,
  BUSINESS_FORM: `${PATHS.BUSINESS}${PATHS.PROFILE}${PATHS.FORM}`,
  BUSINESS_PREVIEW: `${PATHS.BUSINESS}${PATHS.PROFILE}${PATHS.PREVIEW}`,
};

export const E_INVOICE_TYPES = {
  MALAYSIAN: 'Malaysian',
  NON_MALAYSIAN: 'Non-Malaysian',
  BUSINESS: 'Business',
};

export const E_INVOICE_STATUS = {
  REJECT: 'REJECT',
  SUBMITTED: 'SUBMITTED',
  VALID: 'VALID',
  CANCEL: 'CANCEL',
};

export const AVAILABLE_QUERY_E_INVOICE_STATUS_PAGES = {
  HOME: 'home',
  CONSUMER_PREVIEW: 'consumerPreview',
  BUSINESS_PREVIEW: 'businessPreview',
};

export const AVAILABLE_QUERY_E_INVOICE_STATUS_ROUTES = {
  [AVAILABLE_QUERY_E_INVOICE_STATUS_PAGES.HOME]: PAGE_ROUTES.E_INVOICE,
  [AVAILABLE_QUERY_E_INVOICE_STATUS_PAGES.CONSUMER_PREVIEW]: PAGE_ROUTES.CONSUMER_PREVIEW,
  [AVAILABLE_QUERY_E_INVOICE_STATUS_PAGES.BUSINESS_PREVIEW]: PAGE_ROUTES.BUSINESS_PREVIEW,
};

export const GET_E_INVOICE_STATUS_ERROR_CODES = {
  NO_E_INVOICE_SUBMIT_RECORD: '395522',
};

export const SUBMITTED_TIMEOUT_ERROR_MESSAGE = 'SUBMITTED_TIMEOUT';
