export default {
  // fetch onlineStoreInfo
  FETCH_ONLINESTOREINFO_REQUEST: 'VOUCHER/APP/FETCH_ONLINESTOREINFO_REQUEST',
  FETCH_ONLINESTOREINFO_SUCCESS: 'VOUCHER/APP/FETCH_ONLINESTOREINFO_SUCCESS',
  FETCH_ONLINESTOREINFO_FAILURE: 'VOUCHER/APP/FETCH_ONLINESTOREINFO_FAILURE',

  // fetch coreBusiness
  FETCH_COREBUSINESS_REQUEST: 'VOUCHER/APP/FETCH_COREBUSINESS_REQUEST',
  FETCH_COREBUSINESS_SUCCESS: 'VOUCHER/APP/FETCH_COREBUSINESS_SUCCESS',
  FETCH_COREBUSINESS_FAILURE: 'VOUCHER/APP/FETCH_COREBUSINESS_FAILURE',

  // select voucher
  SELECT_VOUCHER: 'VOUCHER/SELECT_VOUCHER',

  // update contact email
  UPDATE_CONTACT_EMAIL: 'VOUCHER/UPDATE_CONTACT_EMAIL',
};
