import Constants from '../../../../../utils/constants';

const { ORDER_STATUS, REFERRER_SOURCE_TYPES } = Constants;

export const ORDER_CANCELLATION_REASONS = {
  TAKING_TOO_LONG_TO_FIND_RIDER: 'takingTooLongToFindRider',
  MERCHANT_CALLED_TO_CANCEL: 'merchantCalledToCancel',
  WRONG_DELIVERY_INFORMATION: 'wrongDeliveryInformation',
  ORDERED_WRONG_ITEM: 'orderedWrongItem',
  CHANGE_OF_MIND: 'changeOfMind',
  OTHERS: 'others',
};

export const ORDER_DELAY_REASON_CODES = {
  RAMADAN: 'ramadan',
  BAD_WEATHER: 'badWeather',
};

export const BEFORE_PAID_STATUS_LIST = [
  ORDER_STATUS.CREATED,
  ORDER_STATUS.PENDING_PAYMENT,
  ORDER_STATUS.PENDING_VERIFICATION,
  ORDER_STATUS.PAYMENT_CANCELLED,
];

export const CASHBACK_CAN_CLAIM = 'Can_Claim';

export const REFERRERS_REQUIRING_PROFILE = [
  REFERRER_SOURCE_TYPES.PAYMENT,
  REFERRER_SOURCE_TYPES.CASHBACK,
  REFERRER_SOURCE_TYPES.PAY_AT_COUNTER,
  REFERRER_SOURCE_TYPES.LOGIN,
];
