export const APP_TYPES = {
  CLEAR_ERROR: 'ORDERING/APP/CLEAR_ERROR',

  // fetch onlineStoreInfo
  FETCH_ONLINESTOREINFO_REQUEST: 'ORDERING/APP/FETCH_ONLINESTOREINFO_REQUEST',
  FETCH_ONLINESTOREINFO_SUCCESS: 'ORDERING/APP/FETCH_ONLINESTOREINFO_SUCCESS',
  FETCH_ONLINESTOREINFO_FAILURE: 'ORDERING/APP/FETCH_ONLINESTOREINFO_FAILURE',

  // message modal
  SET_MESSAGE_INFO: 'ORDERING/APP/SET_MESSAGE_INFO',
  HIDE_MESSAGE_MODAL: 'ORDERING/APP/HIDE_MESSAGE_MODAL',

  // fetch login status
  SHOW_LOGIN_PAGE: 'ORDERING/APP/SHOW_LOGIN_PAGE',
  HIDE_LOGIN_PAGE: 'ORDERING/APP/HIDE_LOGIN_PAGE',
  FETCH_LOGIN_STATUS_REQUEST: 'ORDERING/APP/FETCH_LOGIN_STATUS_REQUEST',
  FETCH_LOGIN_STATUS_SUCCESS: 'ORDERING/APP/FETCH_LOGIN_STATUS_SUCCESS',
  FETCH_LOGIN_STATUS_FAILURE: 'ORDERING/APP/FETCH_LOGIN_STATUS_FAILURE',

  // login
  CREATE_LOGIN_REQUEST: 'ORDERING/APP/CREATE_LOGIN_REQUEST',
  CREATE_LOGIN_SUCCESS: 'ORDERING/APP/CREATE_LOGIN_SUCCESS',
  CREATE_LOGIN_FAILURE: 'ORDERING/APP/CREATE_LOGIN_FAILURE',
  CLEAR_TOKENS: 'ORDERING/APP/CLEAR_TOKENS',

  // get OTP
  GET_OTP_REQUEST: 'ORDERING/APP/GET_OTP_REQUEST',
  GET_OTP_SUCCESS: 'ORDERING/APP/GET_OTP_SUCCESS',
  GET_OTP_FAILURE: 'ORDERING/APP/GET_OTP_FAILURE',

  // OTP
  RESET_OTP_STATUS: 'ORDERING/APP/RESET_OTP_STATUS',
  CREATE_OTP_REQUEST: 'ORDERING/APP/CREATE_OTP_REQUEST',
  CREATE_OTP_SUCCESS: 'ORDERING/APP/CREATE_OTP_SUCCESS',
  CREATE_OTP_FAILURE: 'ORDERING/APP/CREATE_OTP_FAILURE',

  // Fetch available cashback
  FETCH_AVAILABLE_CASHBACK_REQUEST: 'ORDERING/APP/FETCH_AVAILABLE_CASHBACK_REQUEST',
  FETCH_AVAILABLE_CASHBACK_SUCCESS: 'ORDERING/APP/FETCH_AVAILABLE_CASHBACK_SUCCESS',
  FETCH_AVAILABLE_CASHBACK_FAILURE: 'ORDERING/APP/FETCH_AVAILABLE_CASHBACK_FAILURE',
};

export const CART_TYPES = {
  // clear all
  CLEARALL_REQUEST: 'ORDERING/CART/CLEARALL_REQUEST',
  CLEARALL_SUCCESS: 'ORDERING/CART/CLEARALL_SUCCESS',
  CLEARALL_FAILURE: 'ORDERING/CART/CLEARALL_FAILURE',

  // fetch coreBusiness
  FETCH_COREBUSINESS_REQUEST: 'ORDERING/CART/FETCH_COREBUSINESS_REQUEST',
  FETCH_COREBUSINESS_SUCCESS: 'ORDERING/CART/FETCH_COREBUSINESS_SUCCESS',
  FETCH_COREBUSINESS_FAILURE: 'ORDERING/CART/FETCH_COREBUSINESS_FAILURE',

  // Calculator
  TOTAL_CALCULATOR_REQUEST: 'ORDERING/CART/TOTAL_CALCULATOR_REQUEST',
  TOTAL_CALCULATOR_SUCCESS: 'ORDERING/CART/TOTAL_CALCULATOR_SUCCESS',
  TOTAL_CALCULATOR_FAILURE: 'ORDERING/CART/TOTAL_CALCULATOR_FAILURE',
};