export const APP_TYPES = {
  SHOW_ERROR: 'ORDERING/APP/SHOW_ERROR',
  CLEAR_ERROR: 'ORDERING/APP/CLEAR_ERROR',
  CLEAR_API_ERROR: 'ORDERING/APP/CLEAR_API_ERROR',
  PUT_ERROR: 'ORDERING/APP/PUT_ERROR',

  // fetch onlineStoreInfo
  FETCH_ONLINESTOREINFO_REQUEST: 'ORDERING/APP/FETCH_ONLINESTOREINFO_REQUEST',
  FETCH_ONLINESTOREINFO_SUCCESS: 'ORDERING/APP/FETCH_ONLINESTOREINFO_SUCCESS',
  FETCH_ONLINESTOREINFO_FAILURE: 'ORDERING/APP/FETCH_ONLINESTOREINFO_FAILURE',

  // fetch coreBusiness
  FETCH_COREBUSINESS_REQUEST: 'ORDERING/APP/FETCH_COREBUSINESS_REQUEST',
  FETCH_COREBUSINESS_SUCCESS: 'ORDERING/APP/FETCH_COREBUSINESS_SUCCESS',
  FETCH_COREBUSINESS_FAILURE: 'ORDERING/APP/FETCH_COREBUSINESS_FAILURE',

  // message modal
  SET_MESSAGE_INFO: 'ORDERING/APP/SET_MESSAGE_INFO',
  HIDE_MESSAGE_MODAL: 'ORDERING/APP/HIDE_MESSAGE_MODAL',

  // fetch login status
  SHOW_LOGIN_PAGE: 'ORDERING/APP/SHOW_LOGIN_PAGE',
  HIDE_LOGIN_PAGE: 'ORDERING/APP/HIDE_LOGIN_PAGE',
  FETCH_LOGIN_STATUS_REQUEST: 'ORDERING/APP/FETCH_LOGIN_STATUS_REQUEST',
  FETCH_LOGIN_STATUS_SUCCESS: 'ORDERING/APP/FETCH_LOGIN_STATUS_SUCCESS',
  FETCH_LOGIN_STATUS_FAILURE: 'ORDERING/APP/FETCH_LOGIN_STATUS_FAILURE',

  // login
  CREATE_LOGIN_REQUEST: 'ORDERING/APP/CREATE_LOGIN_REQUEST',
  CREATE_LOGIN_SUCCESS: 'ORDERING/APP/CREATE_LOGIN_SUCCESS',
  CREATE_LOGIN_FAILURE: 'ORDERING/APP/CREATE_LOGIN_FAILURE',
  CLEAR_TOKENS: 'ORDERING/APP/CLEAR_TOKENS',

  // Update phone number
  UPDATE_PHONE_NUMBER: 'ORDERING/APP/UPDATE_PHONE_NUMBER',

  // update profile info
  UPDATE_PROFILE_INFO: 'ORDERING/APP/UPDATE_PROFILE_INFO',

  // update otp status
  UPDATE_OTP_STATUS: 'ORDERING/APP/UPDATE_OTP_STATUS',

  // update otp type
  UPDATE_OTP_TYPE: 'ORDERING/APP/UPDATE_OTP_TYPE',

  // fetch profile
  FETCH_PROFILE_REQUEST: 'ORDERING/APP/FETCH_PROFILE_REQUEST',
  FETCH_PROFILE_SUCCESS: 'ORDERING/APP/FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'ORDERING/APP/FETCH_PROFILE_FAILURE',

  // create and update profile
  CREATE_OR_UPDATE_PROFILE_REQUEST: 'ORDERING/APP/CREATE_OR_UPDATE_PROFILE_REQUEST',
  CREATE_OR_UPDATE_PROFILE_SUCCESS: 'ORDERING/APP/CREATE_OR_UPDATE_PROFILE_SUCCESS',
  CREATE_OR_UPDATE_PROFILE_FAILURE: 'ORDERING/APP/CREATE_OR_UPDATE_PROFILE_FAILURE',

  // get OTP
  GET_OTP_REQUEST: 'ORDERING/APP/GET_OTP_REQUEST',
  GET_OTP_SUCCESS: 'ORDERING/APP/GET_OTP_SUCCESS',
  GET_OTP_FAILURE: 'ORDERING/APP/GET_OTP_FAILURE',

  // OTP
  RESET_OTP_STATUS: 'ORDERING/APP/RESET_OTP_STATUS',
  CREATE_OTP_REQUEST: 'ORDERING/APP/CREATE_OTP_REQUEST',
  CREATE_OTP_SUCCESS: 'ORDERING/APP/CREATE_OTP_SUCCESS',
  CREATE_OTP_FAILURE: 'ORDERING/APP/CREATE_OTP_FAILURE',

  // Fetch customer profile
  FETCH_CUSTOMER_PROFILE_REQUEST: 'ORDERING/APP/FETCH_CUSTOMER_PROFILE_REQUEST',
  FETCH_CUSTOMER_PROFILE_SUCCESS: 'ORDERING/APP/FETCH_CUSTOMER_PROFILE_SUCCESS',
  FETCH_CUSTOMER_PROFILE_FAILURE: 'ORDERING/APP/FETCH_CUSTOMER_PROFILE_FAILURE',
};

export const HOME_TYPES = {
  // fetch shoppingCart
  FETCH_SHOPPINGCART_REQUEST: 'ORDERING/HOME/FETCH_SHOPPINGCART_REQUEST',
  FETCH_SHOPPINGCART_SUCCESS: 'ORDERING/HOME/FETCH_SHOPPINGCART_SUCCESS',
  FETCH_SHOPPINGCART_FAILURE: 'ORDERING/HOME/FETCH_SHOPPINGCART_FAILURE',

  // fetch onlineCategory
  FETCH_ONLINECATEGORY_REQUEST: 'ORDERING/HOME/FETCH_ONLINECATEGORY_REQUEST',
  FETCH_ONLINECATEGORY_SUCCESS: 'ORDERING/HOME/FETCH_ONLINECATEGORY_SUCCESS',
  FETCH_ONLINECATEGORY_FAILURE: 'ORDERING/HOME/FETCH_ONLINECATEGORY_FAILURE',

  // mutable removeShoppingCartItem
  REMOVE_SHOPPINGCARTITEM_REQUEST: 'ORDERING/HOME/REMOVE_SHOPPINGCARTITEM_REQUEST',
  REMOVE_SHOPPINGCARTITEM_SUCCESS: 'ORDERING/HOME/REMOVE_SHOPPINGCARTITEM_SUCCESS',
  REMOVE_SHOPPINGCARTITEM_FAILURE: 'ORDERING/HOME/REMOVE_SHOPPINGCARTITEM_FAILURE',

  // fetch productDetail
  FETCH_PRODUCTDETAIL_REQUEST: 'ORDERING/HOME/FETCH_PRODUCTDETAIL__REQUEST',
  FETCH_PRODUCTDETAIL_SUCCESS: 'ORDERING/HOME/FETCH_PRODUCTDETAIL__SUCCESS',
  FETCH_PRODUCTDETAIL_FAILURE: 'ORDERING/HOME/FETCH_PRODUCTDETAIL__FAILURE',

  // mutable addOrUpdateShoppingCartItem
  ADDORUPDATE_SHOPPINGCARTITEM_REQUEST: 'ORDERING/HOME/ADDORUPDATE_SHOPPINGCARTITEM_REQUEST',
  ADDORUPDATE_SHOPPINGCARTITEM_SUCCESS: 'ORDERING/HOME/ADDORUPDATE_SHOPPINGCARTITEM_SUCCESS',
  ADDORUPDATE_SHOPPINGCARTITEM_FAILURE: 'ORDERING/HOME/ADDORUPDATE_SHOPPINGCARTITEM_FAILURE',

  // - or + on home page product item
  DECREASE_PRODUCT_IN_CART: 'ORDERING/HOME/DECREASE_PRODUCT_IN_CART',
  INCREASE_PRODUCT_IN_CART: 'ORDERING/HOME/INCREASE_PRODUCT_IN_CART',

  SET_MENU_LAYOUT_TYPE: 'ORDERING/HOME/SET_MENU_TYPE',

  SET_PRE_ORDER_MODAL_CONFIRM: 'ORDERING/HOME/SET_PRE_ORDER_MODAL_CONFIRM',
};

export const CART_TYPES = {
  // clear all
  CLEARALL_REQUEST: 'ORDERING/CART/CLEARALL_REQUEST',
  CLEARALL_SUCCESS: 'ORDERING/CART/CLEARALL_SUCCESS',
  CLEARALL_FAILURE: 'ORDERING/CART/CLEARALL_FAILURE',

  // clear all by products
  CLEARALL_BY_PRODUCTS_REQUEST: 'ORDERING/CART/CLEARALL_BY_PRODUCTS_REQUEST',
  CLEARALL_BY_PRODUCTS_SUCCESS: 'ORDERING/CART/CLEARALL_BY_PRODUCTS_REQUEST',
  CLEARALL_BY_PRODUCTS_FAILURE: 'ORDERING/CART/CLEARALL_BY_PRODUCTS_REQUEST',

  // fetch order list is pending payment
  FETCH_PENDING_TRANSACTIONS_REQUEST: 'ORDERING/CART/FETCH_PENDING_TRANSACTIONS_REQUEST',
  FETCH_PENDING_TRANSACTIONS_SUCCESS: 'ORDERING/CART/FETCH_PENDING_TRANSACTIONS_SUCCESS',
  FETCH_PENDING_TRANSACTIONS_FAILURE: 'ORDERING/CART/FETCH_PENDING_TRANSACTIONS_FAILURE',

  // Update transactions status
  UPDATE_TRANSACTIONS_STATUS_REQUEST: 'ORDERING/CART/UPDATE_TRANSACTIONS_STATUS_REQUEST',
  UPDATE_TRANSACTIONS_STATUS_SUCCESS: 'ORDERING/CART/UPDATE_TRANSACTIONS_STATUS_SUCCESS',
  UPDATE_TRANSACTIONS_STATUS_FAILURE: 'ORDERING/CART/UPDATE_TRANSACTIONS_STATUS_FAILURE',
};

export const PROMOTION_TYPES = {
  // Apply Promotion code
  APPLY_PROMOTION_CODE_REQUEST: 'ORDERING/PROMOTION/APPLY_PROMOTION_CODE_REQUEST',
  APPLY_PROMOTION_CODE_SUCCESS: 'ORDERING/PROMOTION/APPLY_PROMOTION_CODE_SUCCESS',
  APPLY_PROMOTION_CODE_FAILURE: 'ORDERING/PROMOTION/APPLY_PROMOTION_CODE_FAILURE',

  // Apply Voucher code
  APPLY_VOUCHER_REQUEST: 'ORDERING/PROMOTION/APPLY_VOUCHER_REQUEST',
  APPLY_VOUCHER_SUCCESS: 'ORDERING/PROMOTION/APPLY_VOUCHER_SUCCESS',
  APPLY_VOUCHER_FAILURE: 'ORDERING/PROMOTION/APPLY_VOUCHER_FAILURE',

  APPLY_PROMO_SUCCESS: 'ORDERING/PROMOTION/APPLY_PROMO_SUCCESS',
  APPLY_PROMO_FAILED: 'ORDERING/PROMOTION/APPLY_PROMO_FAILED',

  // DISMISS Promotion code
  DISMISS_PROMOTION_CODE_REQUEST: 'ORDERING/PROMOTION/DISMISS_PROMOTION_CODE_REQUEST',
  DISMISS_PROMOTION_CODE_SUCCESS: 'ORDERING/PROMOTION/DISMISS_PROMOTION_CODE_SUCCESS',
  DISMISS_PROMOTION_CODE_FAILURE: 'ORDERING/PROMOTION/DISMISS_PROMOTION_CODE_FAILURE',

  UPDATE_PROMOTION_CODE: 'ORDERING/PROMOTION/UPDATE_PROMOTION_CODE',
  INITIAL_PROMOTION_CODE: 'ORDERING/PROMOTION/INITIAL_PROMOTION_CODE',
};

export const THANK_YOU_TYPES = {
  // fetch order
  FETCH_ORDER_REQUEST: 'ORDERING/THANK_YOU/FETCH_ORDER_REQUEST',
  FETCH_ORDER_SUCCESS: 'ORDERING/THANK_YOU/FETCH_ORDER_SUCCESS',
  FETCH_ORDER_FAILURE: 'ORDERING/THANK_YOU/FETCH_ORDER_FAILURE',

  FETCH_ORDER_STATUS_REQUEST: 'ORDERING/THANK_YOU/FETCH_ORDER_STATUS_REQUEST',
  FETCH_ORDER_STATUS_SUCCESS: 'ORDERING/THANK_YOU/FETCH_ORDER_STATUS_SUCCESS',
  FETCH_ORDER_STATUS_FAILURE: 'ORDERING/THANK_YOU/FETCH_ORDER_STATUS_FAILURE',

  // fetch CashbackInfo
  FETCH_CASHBACKINFO_REQUEST: 'ORDERING/THANK_YOU/FETCH_CASHBACKINFO_REQUEST',
  FETCH_CASHBACKINFO_SUCCESS: 'ORDERING/THANK_YOU/FETCH_CASHBACKINFO_SUCCESS',
  FETCH_CASHBACKINFO_FAILURE: 'ORDERING/THANK_YOU/FETCH_CASHBACKINFO_FAILURE',

  // create CashbackInfo
  CREATE_CASHBACKINFO_REQUEST: 'ORDERING/THANK_YOU/CREATE_CASHBACKINFO_REQUEST',
  CREATE_CASHBACKINFO_SUCCESS: 'ORDERING/THANK_YOU/CREATE_CASHBACKINFO_SUCCESS',
  CREATE_CASHBACKINFO_FAILURE: 'ORDERING/THANK_YOU/CREATE_CASHBACKINFO_FAILURE',

  // fetch store Hash code
  FETCH_STORE_HASHCODE_REQUEST: 'ORDERING/THANK_YOU/FETCH_STORE_HASHCODE_REQUEST',
  FETCH_STORE_HASHCODE_SUCCESS: 'ORDERING/THANK_YOU/FETCH_STORE_HASHCODE_SUCCESS',
  FETCH_STORE_HASHCODE_FAILURE: 'ORDERING/THANK_YOU/FETCH_STORE_HASHCODE_FAILURE',

  FETCH_STORE_HASHCODE_WITH_TABLEID_REQUEST: 'ORDERING/THANK_YOU/FETCH_STORE_HASHCODE_WITH_TABLEID_REQUEST',
  FETCH_STORE_HASHCODE_WITH_TABLEID_SUCCESS: 'ORDERING/THANK_YOU/FETCH_STORE_HASHCODE_WITH_TABLEID_SUCCESS',
  FETCH_STORE_HASHCODE_WITH_TABLEID_FAILURE: 'ORDERING/THANK_YOU/FETCH_STORE_HASHCODE_WITH_TABLEID_FAILURE',
};

export const REPORT_DRIVER_TYPES = {
  // update input notes
  UPDATE_INPUT_NOTES: 'REPORT_DRIVER/UPDATE_INPUT_NOTES',

  // set upload photo file
  SET_UPLOAD_PHOTO_FILE: 'REPORT_DRIVER/SET_UPLOAD_PHOTO_FILE',

  // remove upload photo file
  REMOVE_UPLOAD_PHOTO_FILE: 'REPORT_DRIVER/REMOVE_UPLOAD_PHOTO_FILE',

  // set upload photo uploaded location
  SET_UPLOAD_PHOTO_LOCATION: 'REPORT_DRIVER/SET_UPLOAD_PHOTO_LOCATION',

  // select reason code
  SELECT_REASON_CODE: 'REPORT_DRIVER/SELECT_REASON_CODE',

  // submit report
  SUBMIT_REPORT_REQUEST: 'REPORT_DRIVER/SUBMIT_REPORT_REQUEST',
  SUBMIT_REPORT_SUCCESS: 'REPORT_DRIVER/SUBMIT_REPORT_SUCCESS',
  SUBMIT_REPORT_FAILURE: 'REPORT_DRIVER/SUBMIT_REPORT_FAILURE',

  // fetch report
  FETCH_REPORT_REQUEST: 'REPORT_DRIVER/FETCH_REPORT_REQUEST',
  FETCH_REPORT_SUCCESS: 'REPORT_DRIVER/FETCH_REPORT_SUCCESS',
  FETCH_REPORT_FAILURE: 'REPORT_DRIVER/FETCH_REPORT_FAILURE',

  // update submit status
  UPDATE_SUBMIT_STATUS: 'REPORT_DRIVER/UPDATE_SUBMIT_STATUS',
};
